export { MedicoService } from './medico/medico.service';
export { HospitalService } from './hospital/hospital.service';
export { ModalUploadService } from './modalUpload/modal-upload.service';
export { LoginGuard } from './guards/login.guard';
export { SettingsService } from './settings/settings.service';
export { SharedService } from './shared/shared.service';
export { SidebarService } from './shared/sidebar.service';
export { UsuarioService } from './usuario/usuario.service';
export { SubirArchivoService } from './subirArchivo/subir-archivo.service';
